import React from 'react';
import { Download } from 'lucide-react';
import { useMyTickets } from '@/hooks/api/useGuestDashboard';
import { formatEventSchedule } from '@/lib/eventSchedule';
import type { GuestTicket } from '@/lib/api/types';

/**
 * src/components/guest/TicketsTab.tsx
 * -------------------------------------------------------------------------
 * The guest dashboard's "Tickets" tab. `ticket.qrCode` is now the URL of the
 * ticket card image rendered by the backend (server/lib/qr) at the moment
 * the ticket was created — it is rendered directly as an <img>, never
 * regenerated client-side.
 * -------------------------------------------------------------------------
 */
async function downloadTicketImage(ticket: GuestTicket) {
  try {
    const response = await fetch(ticket.qrCode);
    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ticket-${ticket.event.title.replace(/\s+/g, '-').toLowerCase()}.png`;
    link.click();
    URL.revokeObjectURL(url);
  } catch {
    // Fall back to just opening it — still lets the guest save it manually.
    window.open(ticket.qrCode, '_blank');
  }
}

export const TicketsTab: React.FC = () => {
  const { data: tickets, isLoading } = useMyTickets();

  if (isLoading) return <div className="py-12 text-center">Loading tickets...</div>;
  if (!tickets || tickets.length === 0) {
    return (
      <div className="py-12 text-center text-muted-foreground">
        No tickets yet. Register for events to get tickets.
      </div>
    );
  }

  const activeTickets = tickets.filter((t) => !t.checkedIn);
  const checkedInTickets = tickets.filter((t) => t.checkedIn);

  return (
    <div className="space-y-8">
      {activeTickets.length > 0 && (
        <div>
          <h3 className="text-[11px] uppercase font-medium tracking-wider mb-4">Active Tickets</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
            {activeTickets.map((ticket) => (
              <TicketCard key={ticket.id} ticket={ticket} />
            ))}
          </div>
        </div>
      )}

      {checkedInTickets.length > 0 && (
        <div>
          <h3 className="text-[11px] uppercase font-medium tracking-wider mb-4 text-muted-foreground">
            Past / Checked In
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6 opacity-50">
            {checkedInTickets.map((ticket) => (
              <TicketCard key={ticket.id} ticket={ticket} drafted />
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

const TicketCard: React.FC<{ ticket: GuestTicket; drafted?: boolean }> = ({ ticket, drafted }) => {
  const schedule = formatEventSchedule(ticket.event.schedule);
  return (
    <div className={`border border-border overflow-hidden ${drafted ? 'grayscale' : ''}`}>
      <div className="bg-foreground text-background px-6 py-3 flex items-center justify-between">
        <span className="text-[11px] uppercase font-medium tracking-wider">{ticket.tierName}</span>
        <span
          className={`text-[11px] uppercase px-2 py-0.5 ${
            ticket.checkedIn ? 'bg-muted-foreground text-background' : 'bg-background text-foreground'
          }`}
        >
          {ticket.checkedIn ? '✓ Checked In' : 'Valid'}
        </span>
      </div>
      <div className="p-6 text-center">
        <h3 className="font-medium text-lg mb-1">{ticket.event.title}</h3>
        <p className="text-[11px] text-muted-foreground uppercase mb-1">
          {schedule.dateLabel} • {schedule.timeLabel}
        </p>
        <p className="text-[11px] text-muted-foreground mb-2">{ticket.event.address}</p>
        {ticket.attendeeName && <p className="text-xs text-foreground mb-1">👤 {ticket.attendeeName}</p>}
        {ticket.checkInCode && (
          <div className="bg-muted px-3 py-2 rounded mb-4 inline-block">
            <span className="text-[11px] uppercase text-muted-foreground">Check-in Code: </span>
            <span className="font-mono font-bold text-sm">{ticket.checkInCode}</span>
          </div>
        )}
        <div className="border-t border-dashed border-border my-4" />
        {/* The ticket card image (QR baked in) generated by the backend. */}
        <div className={`flex justify-center mb-4 ${drafted ? 'opacity-30' : ''}`}>
          <img
            src={ticket.qrCode}
            alt={`Ticket QR for ${ticket.event.title}`}
            className="w-[220px] max-w-full"
          />
        </div>
        {!drafted && (
          <button
            onClick={() => downloadTicketImage(ticket)}
            className="w-full flex items-center justify-center gap-2 bg-foreground text-background py-3 text-[11px] uppercase font-medium hover:bg-primary hover:text-primary-foreground transition-colors"
          >
            <Download size={14} />
            Download Ticket
          </button>
        )}
      </div>
    </div>
  );
};
